add missing include
resolves:
modules/communication/GcodeDispatch.h:29:5: error: 'FILE' does not name a type

Signed-off-by: Richard Marko <rmarko@fedoraproject.org>